### ISSUE TITLE
Milestone 1: Tasks

### ISSUE THREAD

**Issue by arijc76** [UBC-MDS/PyTextPrep#1]
Summary of Milestone 1 tasks:

- [ ] Teamwork contract - Group
- [x] Pick a topic (must be approved) - Group
- [x] Project structure (Git repo) - Josh
- [ ] CONTRIBUTORS in README - Melisa
- [ ] CONDUCT.md - Arijeet
- [ ] CONTRIBUTING.md - Philson
- [ ] README.md - Melisa
- [ ] Functional specifications - 4 empty functions with docstrings - Group
